package edu.eci.cosw.clases;
// Generated 9/04/2016 08:18:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Calificaciones generated by hbm2java
 */
@Entity
@Table(name="CALIFICACIONES"
    ,catalog="coswgr4"
)
public class Calificacion  implements java.io.Serializable {


     private int idcalificacion;
     private String USUARIOS_idCliente;
     private int puntaje;
     private String observacion;
     private String NitEstablecimiento;
     
    public Calificacion() {
    }

	
    public Calificacion(int idcalificacion, String USUARIOS_idCliente, int puntaje) {
        this.idcalificacion = idcalificacion;
        this.USUARIOS_idCliente = USUARIOS_idCliente;
        this.puntaje = puntaje;
    }
    public Calificacion(int idcalificacion, String USUARIOS_idCliente, int puntaje, String observacion, String NitEstablecimiento) {
       this.idcalificacion = idcalificacion;
       this.USUARIOS_idCliente = USUARIOS_idCliente;
       this.puntaje = puntaje;
       this.observacion = observacion;
       this.NitEstablecimiento = NitEstablecimiento;
    }
   
     @Id 

    
    @Column(name="idcalificacion", unique=true, nullable=false)
    public int getIdcalificacion() {
        return this.idcalificacion;
    }
    
    public void setIdcalificacion(int idcalificacion) {
        this.idcalificacion = idcalificacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NitEstablecimiento", nullable=false)
    public String getEstablecimientos() {
        return this.NitEstablecimiento;
    }
    
    public void NitEstablecimiento(String NitEstablecimiento) {
        this.NitEstablecimiento = NitEstablecimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIOS_idCliente", nullable=false)
    public String getUsuarios() {
        return this.USUARIOS_idCliente;
    }
    
    public void setUsuarios(String USUARIOS_idCliente) {
        this.USUARIOS_idCliente = USUARIOS_idCliente;
    }

    
    @Column(name="puntaje", nullable=false)
    public int getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(int puntaje) {
        this.puntaje = puntaje;
    }

    
    @Column(name="observacion", length=100)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


