package edu.eci.cosw.clases;
// Generated 9/04/2016 08:18:08 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Canchas generated by hbm2java
 */
@Entity
@Table(name="CANCHAS"
    ,catalog="coswgr4"
)
public class Cancha  implements java.io.Serializable {


     private CanchasId id;
     private Boolean estadocancha;
     private Integer reservaId;
     private String sNitEstablecimiento;
     
     
    public Cancha() {
    }

	
    public Cancha(CanchasId id) {
        this.id = id;
    }
    public Cancha(CanchasId id,Boolean estadocancha, Integer reservaId) {
       this.id = id;
       this.estadocancha = estadocancha;
       this.reservaId = reservaId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idcancha", column=@Column(name="idcancha", nullable=false) ), 
        @AttributeOverride(name="nitEstablecimiento", column=@Column(name="NitEstablecimiento", nullable=false, length=15) ) } )
    public CanchasId getId() {
        return this.id;
    }
    
    public void setId(CanchasId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NitEstablecimiento", nullable=false, insertable=false, updatable=false)
    public String getEstablecimientos() {
        return this.sNitEstablecimiento;
    }
    
    public void setEstablecimientos(String sNitEstablecimiento) {
        this.sNitEstablecimiento = sNitEstablecimiento;
    }

    @Column(name="estadocancha")
    public Boolean getEstadocancha() {
        return this.estadocancha;
    }
    
    public void setEstadocancha(Boolean estadocancha) {
        this.estadocancha = estadocancha;
    }

    
    @Column(name="reserva_id")
    public Integer getReservaId() {
        return this.reservaId;
    }
    
    public void setReservaId(Integer reservaId) {
        this.reservaId = reservaId;
    }




}


