package edu.eci.cosw.clases;
// Generated 9/04/2016 06:17:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HorariosId generated by hbm2java
 */
@Embeddable
public class HorariosId  implements java.io.Serializable {


     private int dia;
     private Date horaInicial;
     private Date horaFin;
     private int canchasIdcancha;
     private double precio;
     private String nitEstablecimiento;

    public HorariosId() {
    }

    public HorariosId(int dia, Date horaInicial, Date horaFin, int canchasIdcancha, double precio, String nitEstablecimiento) {
       this.dia = dia;
       this.horaInicial = horaInicial;
       this.horaFin = horaFin;
       this.canchasIdcancha = canchasIdcancha;
       this.precio = precio;
       this.nitEstablecimiento = nitEstablecimiento;
    }
   


    @Column(name="Dia", nullable=false)
    public int getDia() {
        return this.dia;
    }
    
    public void setDia(int dia) {
        this.dia = dia;
    }


    @Column(name="HoraInicial", nullable=false, length=8)
    public Date getHoraInicial() {
        return this.horaInicial;
    }
    
    public void setHoraInicial(Date horaInicial) {
        this.horaInicial = horaInicial;
    }


    @Column(name="HoraFin", nullable=false, length=8)
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }


    @Column(name="CANCHAS_idcancha", nullable=false)
    public int getCanchasIdcancha() {
        return this.canchasIdcancha;
    }
    
    public void setCanchasIdcancha(int canchasIdcancha) {
        this.canchasIdcancha = canchasIdcancha;
    }


    @Column(name="Precio", nullable=false, precision=10)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }


    @Column(name="Nit_Establecimiento", nullable=false, length=15)
    public String getNitEstablecimiento() {
        return this.nitEstablecimiento;
    }
    
    public void setNitEstablecimiento(String nitEstablecimiento) {
        this.nitEstablecimiento = nitEstablecimiento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HorariosId) ) return false;
		 HorariosId castOther = ( HorariosId ) other; 
         
		 return (this.getDia()==castOther.getDia())
 && ( (this.getHoraInicial()==castOther.getHoraInicial()) || ( this.getHoraInicial()!=null && castOther.getHoraInicial()!=null && this.getHoraInicial().equals(castOther.getHoraInicial()) ) )
 && ( (this.getHoraFin()==castOther.getHoraFin()) || ( this.getHoraFin()!=null && castOther.getHoraFin()!=null && this.getHoraFin().equals(castOther.getHoraFin()) ) )
 && (this.getCanchasIdcancha()==castOther.getCanchasIdcancha())
 && (this.getPrecio()==castOther.getPrecio())
 && ( (this.getNitEstablecimiento()==castOther.getNitEstablecimiento()) || ( this.getNitEstablecimiento()!=null && castOther.getNitEstablecimiento()!=null && this.getNitEstablecimiento().equals(castOther.getNitEstablecimiento()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDia();
         result = 37 * result + ( getHoraInicial() == null ? 0 : this.getHoraInicial().hashCode() );
         result = 37 * result + ( getHoraFin() == null ? 0 : this.getHoraFin().hashCode() );
         result = 37 * result + this.getCanchasIdcancha();
         result = 37 * result + (int) this.getPrecio();
         result = 37 * result + ( getNitEstablecimiento() == null ? 0 : this.getNitEstablecimiento().hashCode() );
         return result;
   }   


}


