package edu.eci.cosw.clases;
// Generated 9/04/2016 10:36:04 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name="Horarios"
   // ,catalog="coswgr4"
)
public class Horario  implements java.io.Serializable {


     private HorariosId id;
     //private Cancha canchas;

    public Horario() {
    }

    public Horario(HorariosId id,Cancha canchas) {
       this.id = id;
       //this.canchas = canchas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dia", column=@Column(name="Dia", nullable=false) ), 
        @AttributeOverride(name="horaInicial", column=@Column(name="HoraInicial", nullable=false, length=8) ), 
        @AttributeOverride(name="horaFin", column=@Column(name="HoraFin", nullable=false, length=8) ), 
        @AttributeOverride(name="canchasIdcancha", column=@Column(name="CANCHAS_idcancha", nullable=false) ), 
        @AttributeOverride(name="precio", column=@Column(name="Precio", nullable=false, precision=10) ), 
        @AttributeOverride(name="nitEstablecimiento", column=@Column(name="Nit_Establecimiento", nullable=false, length=15) ) } )
    public HorariosId getId() {
        return this.id;
    }
    
    public void setId(HorariosId id) {
        this.id = id;
    }
/*
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="CANCHAS_idcancha", referencedColumnName="idcancha", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="Nit_Establecimiento", referencedColumnName="NitEstablecimiento", nullable=false, insertable=false, updatable=false) } )
    public Cancha getCanchas() {
        return this.canchas;
    }
    
    public void setCanchas(Cancha canchas) {
        this.canchas = canchas;
    }
*/



}


