package edu.eci.cosw.clases;
// Generated 9/04/2016 08:18:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservas generated by hbm2java
 */
@Entity
@Table(name="RESERVAS"
    ,catalog="coswgr4"
)
public class Reserva  implements java.io.Serializable {


     private ReservasId id;
     private Date fechareserva;
     private Double precio;
     private Double tiempo;
     private String usuarioId;
     private String estado;
     private int idCancha;
     private String usuariosIdCliente;

    public Reserva() {
    }

	
    public Reserva(ReservasId id, String usuarioId, int idCancha, String usuariosIdCliente) {
        this.id = id;
        this.usuarioId = usuarioId;
        this.idCancha = idCancha;
        this.usuariosIdCliente = usuariosIdCliente;
    }
    public Reserva(ReservasId id, Date fechareserva, Double precio, Double tiempo, String usuarioId, String estado, int idCancha, String usuariosIdCliente) {
       this.id = id;
       this.fechareserva = fechareserva;
       this.precio = precio;
       this.tiempo = tiempo;
       this.usuarioId = usuarioId;
       this.estado = estado;
       this.idCancha = idCancha;
       this.usuariosIdCliente = usuariosIdCliente;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idreserva", column=@Column(name="idreserva", nullable=false) ), 
        @AttributeOverride(name="nitEstablecimiento", column=@Column(name="Nit_Establecimiento", nullable=false, length=15) ) } )
    public ReservasId getId() {
        return this.id;
    }
    
    public void setId(ReservasId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechareserva", length=10)
    public Date getFechareserva() {
        return this.fechareserva;
    }
    
    public void setFechareserva(Date fechareserva) {
        this.fechareserva = fechareserva;
    }

    
    @Column(name="precio", precision=8, scale=3)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    
    @Column(name="tiempo", precision=5, scale=3)
    public Double getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(Double tiempo) {
        this.tiempo = tiempo;
    }

    
    @Column(name="usuario_id", nullable=false, length=10)
    public String getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(String usuarioId) {
        this.usuarioId = usuarioId;
    }

    
    @Column(name="Estado", length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="IdCancha", nullable=false)
    public int getIdCancha() {
        return this.idCancha;
    }
    
    public void setIdCancha(int idCancha) {
        this.idCancha = idCancha;
    }

    
    @Column(name="USUARIOS_idCliente", nullable=false, length=10)
    public String getUsuariosIdCliente() {
        return this.usuariosIdCliente;
    }
    
    public void setUsuariosIdCliente(String usuariosIdCliente) {
        this.usuariosIdCliente = usuariosIdCliente;
    }




}


