package edu.eci.cosw.clases;
// Generated 9/04/2016 10:36:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name="RESERVAS"
   // ,catalog="coswgr4"
)
public class Reserva  implements java.io.Serializable {


     private ReservasId id;
     //private Cancha canchas;
     //private Usuario usuarios;
     private Date fechareserva;
     private Double precio;
     private Double tiempo;
     private String usuarioId;
     private String estado;
     private int IdCancha;

    public Reserva() {
    }

	
    public Reserva(ReservasId id,Cancha canchas, Usuario usuarios, String usuarioId) {
        this.id = id;
        //this.canchas = canchas;
        //this.usuarios = usuarios;
        this.usuarioId = usuarioId;
    }
    public Reserva(ReservasId id,Cancha canchas, Usuario usuarios, Date fechareserva, Double precio, Double tiempo, String usuarioId, String estado) {
       this.id = id;
       //this.canchas = canchas;
       //this.usuarios = usuarios;
       this.fechareserva = fechareserva;
       this.precio = precio;
       this.tiempo = tiempo;
       this.usuarioId = usuarioId;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idreserva", column=@Column(name="idreserva", nullable=false) ), 
        @AttributeOverride(name="nitEstablecimiento", column=@Column(name="Nit_Establecimiento", nullable=false, length=15) ) } )
    public ReservasId getId() {
        return this.id;
    }
    
    public void setId(ReservasId id) {
        this.id = id;
    }
/*
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="IdCancha", referencedColumnName="idcancha", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="Nit_Establecimiento", referencedColumnName="NitEstablecimiento", nullable=false, insertable=false, updatable=false) } )
    public Cancha getCanchas() {
        return this.canchas;
    }
    
    public void setCanchas(Cancha canchas) {
        this.canchas = canchas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIOS_idCliente", nullable=false)
    public Usuario getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuario usuarios) {
        this.usuarios = usuarios;
    }
*/
    @Temporal(TemporalType.DATE)
    @Column(name="fechareserva", length=10)
    public Date getFechareserva() {
        return this.fechareserva;
    }
    
    public void setFechareserva(Date fechareserva) {
        this.fechareserva = fechareserva;
    }

    
    @Column(name="precio", precision=8, scale=3)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    
    @Column(name="tiempo", precision=5, scale=3)
    public Double getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(Double tiempo) {
        this.tiempo = tiempo;
    }

    
    @Column(name="USUARIOS_idCliente", nullable=false, length=10)
    public String getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(String usuarioId) {
        this.usuarioId = usuarioId;
    }

    
    @Column(name="IdCancha", nullable = false)
    public int getIdCancha() {
        return this.IdCancha;
    }
    
    public void setIdCancha(int IdCancha) {
        this.IdCancha = IdCancha;
    }
    
    @Column(name="Estado", length=50)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


