package edu.eci.cosw.clases;
// Generated 9/04/2016 10:36:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 *Usuarios generated by hbm2java
 */
@Entity
@Table(name="USUARIOS"
    ,catalog="coswgr4"
)
public class Usuario  implements java.io.Serializable {


     private String idCliente;
     private String nombre;
     private String apellido;
     private String telefono;
     private String email;
     private String password;
     private Set<Calificacion> calificacioneses = new HashSet<Calificacion>(0);
     private Set<Reserva> reservases = new HashSet<Reserva>(0);

    public Usuario() {
    }

	
    public Usuario(String idCliente, String nombre, String apellido, String password) {
        this.idCliente = idCliente;
        this.nombre = nombre;
        this.apellido = apellido;
        this.password = password;
    }
    public Usuario(String idCliente, String nombre, String apellido, String telefono, String email, String password, Set<Calificacion> calificacioneses, Set<Reserva> reservases) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.email = email;
       this.password = password;
       this.calificacioneses = calificacioneses;
       this.reservases = reservases;
    }
   
     @Id 

    
    @Column(name="idCliente", unique=true, nullable=false, length=10)
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=20)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="telefono", length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
@JoinColumn(name="USUARIOS_idCliente", nullable=false)
    public Set<Calificacion> getCalificacioneses() {
        return this.calificacioneses;
    }
    
    public void setCalificacioneses(Set<Calificacion> calificacioneses) {
        this.calificacioneses = calificacioneses;
    }

@OneToMany(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
@JoinColumn(name="USUARIOS_idCliente", nullable=false)
    public Set<Reserva> getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set<Reserva> reservases) {
        this.reservases = reservases;
    }
}
